/*
//------------------------------------------------------------------------------
// Author - Diyar United Company
// Dated  - 21 July 2014
// Project- CMS Customer Service
//------------------------------------------------------------------------------
*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-07-24 - 15:57:37
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System.Collections.Generic;
using DUC.CMS.CustomerService.BLL.Dtos;
using DUC.CMS.CustomerService.DAL;

namespace DUC.CMS.CustomerService.BLL.Mappers
{

    /// <summary>
    /// Assembler for <see cref="CARD_CENTER"/> and <see cref="CardCenterDTO"/>.
    /// </summary>
    public static partial class CardCenterMapper
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="CardCenterDTO"/> converted from <see cref="CARD_CENTER"/>.</param>
        static partial void OnDTO(this CARD_CENTER entity, CardCenterDTO dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="CARD_CENTER"/> converted from <see cref="CardCenterDTO"/>.</param>
        static partial void OnEntity(this CardCenterDTO dto, CARD_CENTER entity);

        /// <summary>
        /// Converts this instance of <see cref="CardCenterDTO"/> to an instance of <see cref="CARD_CENTER"/>.
        /// </summary>
        /// <param name="dto"><see cref="CardCenterDTO"/> to convert.</param>
        public static CARD_CENTER ToEntity(this CardCenterDTO dto)
        {
            if (dto == null) return null;

            var entity = new CARD_CENTER();

            entity.CARD_CENTER_ID = dto.CardCentreID;
           // entity.LOCATION_ID = (int) dto.LastUpdatedLocationID ;
            entity.NAME = dto.Name;
            entity.IS_ACTIVE = (short)(dto.IsActive ? 1 : 0);
            entity.LAST_UPDATED_USER_ID = dto.LastUpdatedUserId;
            entity.LAST_UPDATED_DATE = dto.LastUpdatedDate;
            entity.LAST_LOCATION_ID = dto.LastUpdatedLocationID;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="CARD_CENTER"/> to an instance of <see cref="CardCenterDTO"/>.
        /// </summary>
        /// <param name="entity"><see cref="CARD_CENTER"/> to convert.</param>
        public static CardCenterDTO ToDTO(this CARD_CENTER entity)
        {
            if (entity == null) return null;

            var dto = new CardCenterDTO();

            dto.CardCentreID = entity.CARD_CENTER_ID;
            dto.LastUpdatedLocationID = entity.LOCATION.LOCATION_ID;
            dto.Name = entity.NAME;
            dto.Name_ar = entity.AR_NAME;
            dto.IsActive = entity.IS_ACTIVE == 1;
            dto.LastUpdatedUserId = entity.LAST_UPDATED_USER_ID;
            dto.LastUpdatedDate = entity.LAST_UPDATED_DATE;
            dto.LastUpdatedLocationID = (int?)entity.LAST_LOCATION_ID;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="CardCenterDTO"/> to an instance of <see cref="CARD_CENTER"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<CARD_CENTER> ToEntities(this IEnumerable<CardCenterDTO> dtos)
        {
            return LinqExtension.ToEntity<CARD_CENTER, CardCenterDTO>(dtos, ToEntity);

        }

        /// <summary>
        /// Converts each instance of <see cref="CARD_CENTER"/> to an instance of <see cref="CardCenterDTO"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<CardCenterDTO> ToDTOs(this IEnumerable<CARD_CENTER> entities)
        {
            return LinqExtension.ToDTO<CARD_CENTER, CardCenterDTO>(entities, ToDTO);

        }

    }
}
