/*
//------------------------------------------------------------------------------
// Author - Diyar United Company
// Dated  - 21 July 2014
// Project- CMS Customer Service
//------------------------------------------------------------------------------
*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-08-13 - 15:00:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace DUC.CMS.CustomerService.BLL.Dtos
{
    [DataContract()]
    public partial class AccountManagerDTO :BaseDTO
    {
        [DataMember()]
        public Int32? AccountManagerID { get; set; }

        [DataMember()]
        public Nullable<Int32> UserID { get; set; }

        [DataMember()]
        public String Name { get; set; }

        [DataMember()]
        public String Mobile { get; set; }

        [DataMember()]
        public String Phone { get; set; }

        [DataMember()]
        public String Email { get; set; }

        [DataMember()]
        public String Fax { get; set; }

    }
}
