/*
//------------------------------------------------------------------------------
// Author - Diyar United Company
// Dated  - 21 July 2014
// Project- CMS Customer Service
//------------------------------------------------------------------------------
*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-07-21 - 17:40:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace DUC.CMS.CustomerService.BLL.Dtos
{
    [DataContract()]
    public partial class IdentificationTypeDTO : BaseDTO
    {
        [DataMember()]
        public Int32 IdentificationTypeId { get; set; }

        [DataMember()]
        public String ENName { get; set; }

        [DataMember()]
        public String ARName { get; set; }

        [DataMember()]
        public List<Int32> CustomerId { get; set; }

        public IdentificationTypeDTO()
        {
        }
    }
}
