/*
//------------------------------------------------------------------------------
// Author - Diyar United Company
// Dated  - 21 July 2014
// Project- CMS Customer Service
//------------------------------------------------------------------------------
*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-07-22 - 07:52:20
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace DUC.CMS.CustomerService.BLL.Dtos
{
    [DataContract()]
    public partial class NotificationLanguageDTO : BaseDTO
    {
        [DataMember()]
        public Int32 NOTIFICATION_LANGUAGE_ID { get; set; }

        [DataMember()]
        public String EN_NAME { get; set; }

        [DataMember()]
        public Int16 IS_ACTIVE { get; set; }

        [DataMember()]
        public String AR_NAME { get; set; }

        public NotificationLanguageDTO()
        {
        }

        public NotificationLanguageDTO(Int32 nOTIFICATION_LANGUAGE_ID, String eN_NAME, Int16 iS_ACTIVE, String aR_NAME)
        {
			this.NOTIFICATION_LANGUAGE_ID = nOTIFICATION_LANGUAGE_ID;
			this.EN_NAME = eN_NAME;
			this.IS_ACTIVE = iS_ACTIVE;
			this.AR_NAME = aR_NAME;
        }
    }
}
