/*
//------------------------------------------------------------------------------
// Author - Diyar United Company
// Dated  - 21 July 2014
// Project- CMS Customer Service
//------------------------------------------------------------------------------
*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-07-24 - 13:33:13
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace DUC.CMS.CustomerService.BLL.Dtos
{
    [DataContract()]
    public partial class PAYMENT_METHODDTO : BaseDTO
    {
        [DataMember()]
        public Int32 PAYMENT_METHOD_ID { get; set; }

        [DataMember()]
        public String EN_PAYMENT_METHOD { get; set; }

        [DataMember()]
        public Int16 IS_ACTIVE { get; set; }

        [DataMember()]
        public String AR_PAYMENT_METHOD { get; set; }

        [DataMember()]
        public List<Int32> CUSTOMER_PAYMENT_PAYMENT_ID { get; set; }

        public PAYMENT_METHODDTO()
        {
        }

        public PAYMENT_METHODDTO(Int32 pAYMENT_METHOD_ID, String eN_PAYMENT_METHOD, Int16 iS_ACTIVE, String aR_PAYMENT_METHOD, List<Int32> cUSTOMER_PAYMENT_PAYMENT_ID)
        {
			this.PAYMENT_METHOD_ID = pAYMENT_METHOD_ID;
			this.EN_PAYMENT_METHOD = eN_PAYMENT_METHOD;
			this.IS_ACTIVE = iS_ACTIVE;
			this.AR_PAYMENT_METHOD = aR_PAYMENT_METHOD;
			this.CUSTOMER_PAYMENT_PAYMENT_ID = cUSTOMER_PAYMENT_PAYMENT_ID;
        }
    }
}
