/*
//------------------------------------------------------------------------------
// Author - Diyar United Company
// Dated  - 21 July 2014
// Project- CMS Customer Service
//------------------------------------------------------------------------------
*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-07-21 - 07:20:31
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

namespace DUC.CMS.CustomerService.BLL.Dtos
{
    [DataContract()]
    public partial class RESTRICTION_GROUP_QUANTITYDto : BaseDTO
    {
        [DataMember()]
        public Int32 RESTRICTION_GROUP_ID { get; set; }

        [DataMember()]
        public Int32 PRODUCT_ID { get; set; }

        [DataMember()]
        public Int32 FREQUENCY_ID { get; set; }

        [DataMember()]
        public decimal? ALLOWED_QUANTITY { get; set; }

        [DataMember()]
        public Int16 IS_ACTIVE { get; set; }

        [DataMember()]
        public Nullable<Int32> LAST_UPDATED_USER_ID { get; set; }

        [DataMember()]
        public Nullable<DateTime> LAST_UPDATED_DATE { get; set; }

        [DataMember()]
        public Int32 RESTRICTION_GROUP_RESTRICTION_GROUP_ID { get; set; }
    }
}
