/*
//------------------------------------------------------------------------------
// Author - Diyar United Company
// Dated  - 21 July 2014
// Project- CMS Customer Service
//------------------------------------------------------------------------------
*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-07-21 - 07:20:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace DUC.CMS.CustomerService.BLL.Dtos
{
    [DataContract()]
    public partial class TOKEN_TYPEDto : BaseDTO
    {
        [DataMember()]
        public Int32 TOKEN_TYPE_ID { get; set; }

        [DataMember()]
        public String EN_NAME { get; set; }

        [DataMember()]
        public Int16 IS_ACTIVE { get; set; }

        [DataMember()]
        public String DESCRIPTION { get; set; }

        [DataMember()]
        public String AR_NAME { get; set; }

        [DataMember()]
        public List<Int32> TOKENs_TOKEN_ID { get; set; }
    }
}
