/*
//------------------------------------------------------------------------------
// Author - Diyar United Company
// Dated  - 21 July 2014
// Project- CMS Customer Service
//------------------------------------------------------------------------------
*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-07-21 - 07:20:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace DUC.CMS.CustomerService.BLL.Dtos
{
    [DataContract()]
    public partial class VEHICLE_INFODto : BaseDTO
    {
        [DataMember()]
        public Int32 VEHICLE_INFO_ID { get; set; }

        [DataMember()]
        public String PLATE_NUMBER { get; set; }

        [DataMember()]
        public Nullable<Int32> COLOR_ID { get; set; }

        [DataMember()]
        public String PLATE_COLOUR_ID { get; set; }

        [DataMember()]
        public Nullable<Int32> STATE_ID { get; set; }

        [DataMember()]
        public String CHASSIS_NUMBER { get; set; }

        [DataMember()]
        public Nullable<Int32> VEHICLE_REGISTER_ID { get; set; }

        [DataMember()]
        public Nullable<Int32> VEHICLE_TYPE_ID { get; set; }

        [DataMember()]
        public Int16 IS_ACTIVE { get; set; }

        [DataMember()]
        public List<Int32> TOKENs_TOKEN_ID { get; set; }

        [DataMember()]
        public Int32 VEHICLE_COLOR_VEHICLE_COLOR_ID { get; set; }

        [DataMember()]
        public Int32 VEHICLE_REGISTER_VEHICLE_REGISTER_ID { get; set; }

        [DataMember()]
        public Int32 VEHICLE_STATE_VEHICLE_STATE_ID { get; set; }

        [DataMember()]
        public Int32 VEHICLE_TYPE_VEHICLE_TYPE_ID { get; set; }
    }
}
