/*
//------------------------------------------------------------------------------
// Author - Diyar United Company
// Dated  - 21 July 2014
// Project- CMS Customer Service
//------------------------------------------------------------------------------
*/
//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2014-07-21 - 07:20:34
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace DUC.CMS.CustomerService.BLL.Dtos
{
    [DataContract()]
    public partial class VEHICLE_MODELDto : BaseDTO
    {
        [DataMember()]
        public Int32 VEHICLE_MODEL_ID { get; set; }

        [DataMember()]
        public String EN_NAME { get; set; }

        [DataMember()]
        public Int16 IS_ACTIVE { get; set; }

        [DataMember()]
        public String AR_NAME { get; set; }

        [DataMember()]
        public Int32 VEHICLE_MAKE_ID { get; set; }

        [DataMember()]
        public Int32 VEHICLE_MAKE_VEHICLE_MAKE_ID { get; set; }

        [DataMember()]
        public List<Int32> VEHICLE_REGISTER_VEHICLE_REGISTER_ID { get; set; }
    }
}
