//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public ADDRESS()
        {
            this.CUSTOMER = new HashSet<CUSTOMER>();
            this.CUSTOMER1 = new HashSet<CUSTOMER>();
            this.CUSTOMER2 = new HashSet<CUSTOMER>();
            this.LOCATION = new HashSet<LOCATION>();
            this.BENEFICIARies = new HashSet<BENEFICIARY>();
        }
    
        public int ADDRESS_ID { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public string POST_CODE { get; set; }
        public string DETAILED_ADDRESS { get; set; }
        public short IS_ACTIVE { get; set; }
        public string FAX { get; set; }
        public string PHONE_NUMBER { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual ICollection<CUSTOMER> CUSTOMER { get; set; }
        public virtual ICollection<CUSTOMER> CUSTOMER1 { get; set; }
        public virtual ICollection<CUSTOMER> CUSTOMER2 { get; set; }
        public virtual CITY CITY { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
        public virtual AREA AREA { get; set; }
        public virtual ICollection<LOCATION> LOCATION { get; set; }
        public virtual ICollection<BENEFICIARY> BENEFICIARies { get; set; }
    }
}
