//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARY_GROUP
    {
        public BENEFICIARY_GROUP()
        {
            this.BENEFICIARies = new HashSet<BENEFICIARY>();
        }
    
        public int GROUP_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public string EN_GROUP_NAME { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string AR_GROUP_NAME { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<decimal> CODE_COMBINATION_ID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ICollection<BENEFICIARY> BENEFICIARies { get; set; }
    }
}
