//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARY
    {
        public int BENEFICIARY_ID { get; set; }
        public string CODE { get; set; }
        public int CUSTOMER_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public Nullable<int> ADDRESS_ID { get; set; }
        public string NAME { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string PIN { get; set; }
        public int LANGUAGE_ID { get; set; }
        public Nullable<int> IDENTIFICATION_TYPE_ID { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<int> NATIONALILTY_ID { get; set; }
        public Nullable<int> NOTIFICATION_CHANNEL_ID { get; set; }
        public Nullable<int> NOTIFICATION_LANGUAGE_ID { get; set; }
        public Nullable<int> FAMILY_ID { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public int BENEFICIARY_STATUS_ID { get; set; }
        public Nullable<int> BENEFICIARY_STATUS_REASON_ID { get; set; }
        public short IS_STATUS_INHERITED { get; set; }
        public short IS_DISABILITY { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<System.DateTime> REGISTRATION_DATE { get; set; }
        public short IS_VIP { get; set; }
        public short IS_DISABLED { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<int> STATUS_CHANGE_LOG_ID { get; set; }
        public string GENDER { get; set; }
        public short IS_CUSTOMER_DEFAULT { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual BENEFICIARY_GROUP BENEFICIARY_GROUP { get; set; }
        public virtual NOTIFICATION_LANGUAGE NOTIFICATION_LANGUAGE { get; set; }
        public virtual NOTIFICATION_CHANNEL NOTIFICATION_CHANNEL { get; set; }
        public virtual LANGUAGE LANGUAGE { get; set; }
        public virtual NATIONALITY NATIONALITY { get; set; }
        public virtual FAMILY FAMILY { get; set; }
        public virtual IDENTIFICATION_TYPE IDENTIFICATION_TYPE { get; set; }
        public virtual BENEFICIARY_STATUS BENEFICIARY_STATUS { get; set; }
    }
}
