//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARY_STATUS
    {
        public BENEFICIARY_STATUS()
        {
            this.BENEFICIARY_STATUS_REASON = new HashSet<BENEFICIARY_STATUS_REASON>();
            this.BENEFICIARY_STATUS_CHANGE_LOG = new HashSet<BENEFICIARY_STATUS_CHANGE_LOG>();
            this.BENEFICIARies = new HashSet<BENEFICIARY>();
        }
    
        public int BENEFICIARY_STATUS_ID { get; set; }
        public string AR_BENEFICIARY_STATUS { get; set; }
        public short IS_ACTIVE { get; set; }
        public string EN_BENEFICIARY_STATUS { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual ICollection<BENEFICIARY_STATUS_REASON> BENEFICIARY_STATUS_REASON { get; set; }
        public virtual ICollection<BENEFICIARY_STATUS_CHANGE_LOG> BENEFICIARY_STATUS_CHANGE_LOG { get; set; }
        public virtual ICollection<BENEFICIARY> BENEFICIARies { get; set; }
    }
}
