//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARD_CENTER
    {
        public CARD_CENTER()
        {
            this.PERSONALIZATION_ORDER = new HashSet<PERSONALIZATION_ORDER>();
        }
    
        public int CARD_CENTER_ID { get; set; }
        public string NAME { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string AR_NAME { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<decimal> INTEGRATION_ID { get; set; }
        public Nullable<short> CAN_PRINT_IDENTITY_ONLY { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
        public virtual ICollection<PERSONALIZATION_ORDER> PERSONALIZATION_ORDER { get; set; }
    }
}
