//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CITY
    {
        public CITY()
        {
            this.ADDRESS = new HashSet<ADDRESS>();
            this.AREA = new HashSet<AREA>();
        }
    
        public int CITY_ID { get; set; }
        public string EN_NAME { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public string AR_NAME { get; set; }
        public int COUNTRY_ID { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public string INTEGRATION_ID { get; set; }
    
        public virtual ICollection<ADDRESS> ADDRESS { get; set; }
        public virtual ICollection<AREA> AREA { get; set; }
        public virtual COUNTRY COUNTRY { get; set; }
    }
}
