//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_TYPE
    {
        public CONTACT_TYPE()
        {
            this.CUSTOMER_CONTACT = new HashSet<CUSTOMER_CONTACT>();
            this.RQST_REQUEST_CUSTOMER_CONTACT = new HashSet<RQST_REQUEST_CUSTOMER_CONTACT>();
        }
    
        public int CONTACT_TYPE_ID { get; set; }
        public string AR_NAME { get; set; }
        public string EN_NAME { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual ICollection<CUSTOMER_CONTACT> CUSTOMER_CONTACT { get; set; }
        public virtual ICollection<RQST_REQUEST_CUSTOMER_CONTACT> RQST_REQUEST_CUSTOMER_CONTACT { get; set; }
    }
}
