//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTAccountTrnsBalance
    {
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> PAYMENT_TYPE_ID { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string SERVICE_OR_PROD_NAME { get; set; }
        public string LOCATION_NAME { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public string BENEFICIARY_NAME { get; set; }
        public string BENEFICIARY_NO { get; set; }
        public Nullable<decimal> VAT_PERCENT { get; set; }
        public string VAT_INVOICE_NUMBER { get; set; }
        public string VAT_CODE { get; set; }
        public string TOKEN_TYPE_NAME { get; set; }
        public string TOKEN_SERIAL { get; set; }
        public Nullable<int> TRANS_ID { get; set; }
        public Nullable<decimal> VAT_AMOUNT { get; set; }
        public Nullable<short> ISPREMIUMSERVICETRX { get; set; }
        public string Is_Split { get; set; }
    }
}
