//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTAccountSegmentDTO
    {
        public int RuleID { get; set; }
        public string CustomerCode { get; set; }
        public int IsPremium { get; set; }
        public int AccountTypeID { get; set; }
        public int EmiratesID { get; set; }
        public short IsActive { get; set; }
        public int FamilyID { get; set; }
    }
}
