//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTAccountBalance
    {
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> InitialBalance { get; set; }
        public Nullable<decimal> FinalBalance { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> PaymentTypeID { get; set; }
        public string TransactionType { get; set; }
        public string TransactionTypeAR { get; set; }
    }
}
