//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTAccountEOMSegmentDTO
    {
        public int RuleID { get; set; }
        public string CustomerCode { get; set; }
        public int NationalityID { get; set; }
        public int ClassificationID { get; set; }
        public short IsActive { get; set; }
    }
}
