//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTAccountTokenSearch
    {
        public string TokenName { get; set; }
        public string BeneficiaryName { get; set; }
        public Nullable<int> RestrictionGroupID { get; set; }
        public Nullable<int> TokenStatusID { get; set; }
        public Nullable<System.DateTime> RegisterFromDate { get; set; }
        public Nullable<System.DateTime> RegisterToDate { get; set; }
        public Nullable<int> TokenTypeID { get; set; }
        public string TokenSerial { get; set; }
        public string TokenCode { get; set; }
        public string IDNumber { get; set; }
        public string VehicleNo { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> EmployeeID { get; set; }
    }
}
