//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTBatchToken
    {
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> BeneficiaryID { get; set; }
        public string TokenName { get; set; }
        public Nullable<int> TokenTypeId { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> RestrictionGroupId { get; set; }
        public Nullable<int> TokenStatusId { get; set; }
        public Nullable<int> TokenStatusReasonId { get; set; }
        public Nullable<short> IsActive { get; set; }
        public Nullable<int> CardCentreID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<int> ReasonID { get; set; }
        public Nullable<int> PersonalizationOrderStatusID { get; set; }
        public Nullable<int> PersonalizationOrderTypeID { get; set; }
        public Nullable<int> IdentificationTypeID { get; set; }
        public string IdentityNumber { get; set; }
        public int PersonalizationOrderID { get; set; }
    }
}
