//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTBatchTokenVehicleMap
    {
        public Nullable<int> TokenID { get; set; }
        public string PlateNumber { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> StateID { get; set; }
        public string PlateColorID { get; set; }
        public string ChassisNumber { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string WorkOrderNumber { get; set; }
        public Nullable<int> WorkOrderStatusID { get; set; }
        public Nullable<int> WorkOrderStatusReasonID { get; set; }
        public Nullable<int> VehicleDepotID { get; set; }
        public Nullable<System.DateTime> AppointDateTime { get; set; }
        public Nullable<System.DateTime> ServiceDateTime { get; set; }
        public Nullable<int> WorkOrderTypeID { get; set; }
        public Nullable<int> LastUpdatedUser { get; set; }
        public string RecipientIdNumber { get; set; }
        public Nullable<int> RecipientTypeID { get; set; }
        public Nullable<int> LastLocationID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
