//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTBeneficiarySegmentDTO
    {
        public int RuleID { get; set; }
        public System.DateTime FromDOB { get; set; }
        public System.DateTime ToDOB { get; set; }
        public short IsVIP { get; set; }
        public int NationalityID { get; set; }
        public short HasDisability { get; set; }
        public short IsActive { get; set; }
    }
}
