//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTBeneficiaryRestrictionInput
    {
        public Nullable<int> BeneficiaryId { get; set; }
        public Nullable<int> TimeFrequencyId { get; set; }
        public Nullable<decimal> AllowedAmount { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
        public Nullable<int> LastLocationId { get; set; }
    }
}
