//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTBeneficiaryStatusHistory
    {
        public Nullable<int> customer_id { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public Nullable<int> BENEFICIARY_STATUS_ID { get; set; }
        public string EN_BENEFICIARY_STATUS { get; set; }
        public Nullable<int> BENEFICIARY_STATUS_REASON_ID { get; set; }
        public string BENEFICIARY_STATUS_REASON_NAME { get; set; }
        public Nullable<System.DateTime> STATUS_CHANGE_DATE { get; set; }
        public string CODE { get; set; }
        public string USER_NAME { get; set; }
        public string AR_BENEFICIARY_STATUS { get; set; }
        public string BENEFICIARY_STATUS_REASON_NAME_ar { get; set; }
    }
}
