//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTBillingFrequency
    {
        public int BILLING_FREQUENCY_ID { get; set; }
        public string EN_NAME { get; set; }
        public int IS_ACTIVE { get; set; }
        public string AR_NAME { get; set; }
        public Nullable<int> DURATION { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<int> LAST_LOCATION_ID { get; set; }
    }
}
