//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTBillToDetails
    {
        public string BILL_TO_NUMBER { get; set; }
        public string BILL_TO_ADDRESS { get; set; }
        public string BILL_TO_FAX { get; set; }
        public string PO_BOX { get; set; }
        public string ADDRESS_DETAILS { get; set; }
    }
}
