//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerBillingDetail
    {
        public int CUSTOMER_ID { get; set; }
        public int INVOICE_ID { get; set; }
        public System.DateTime billing_date { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_FROM { get; set; }
        public Nullable<System.DateTime> DATE_TO { get; set; }
        public string billing_period_en { get; set; }
        public int STATUS_ID { get; set; }
        public string STATUS_NAME { get; set; }
        public string STATUS_NAME_ar { get; set; }
        public string billing_period_AR { get; set; }
    }
}
