//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerInformation
    {
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> BillingAddressID { get; set; }
        public Nullable<int> ISMULTIPLEBILLTODETAILS { get; set; }
        public Nullable<int> MAXCREDITLIMIT { get; set; }
        public Nullable<int> AccountManagerID { get; set; }
        public Nullable<int> CustomerAccountTypeID { get; set; }
        public string AccManagerMobile { get; set; }
        public string AccManagerFax { get; set; }
        public string ShippingAddress { get; set; }
        public string CorporateAddress { get; set; }
        public string CorporateAddressEmirate { get; set; }
        public string CorporateAddressArea { get; set; }
        public string CorporateAddressPhone { get; set; }
        public string CorporateAddressFax { get; set; }
        public string BillingAddressEmirateID { get; set; }
        public string BillingAddressEmirate { get; set; }
        public string BillingAddressArea { get; set; }
        public string BillingAddressPhone { get; set; }
        public string BillingAddressFax { get; set; }
        public string ShippingAddressEmirate { get; set; }
        public string ShippingAddressArea { get; set; }
        public string ShippingAddressPhone { get; set; }
        public string ShippingAddressFax { get; set; }
        public Nullable<int> CorporateAddressID { get; set; }
        public Nullable<int> CorporateAddressEmirateID { get; set; }
        public Nullable<int> BillingAddressAreaID { get; set; }
        public Nullable<int> ShippingAddressID { get; set; }
        public Nullable<int> ShippingAddressEmirateID { get; set; }
        public Nullable<int> ShippingAddressAreaID { get; set; }
        public Nullable<int> PaymentTerms { get; set; }
        public Nullable<int> CorporateAddressAreaID { get; set; }
        public string CustomerName { get; set; }
        public string BillingAddress { get; set; }
        public string AccountStatus { get; set; }
        public string AccPrimaryContactName { get; set; }
        public string AccNationalID { get; set; }
        public string AccountManager { get; set; }
        public string AccManagerEmail { get; set; }
        public string AccManagerPhone { get; set; }
        public string AccManagerJobTitle { get; set; }
        public string FinancialAccountNumber { get; set; }
        public string CustomerAccountType { get; set; }
        public string CustomerAccountType_ar { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<int> Customer_Class { get; set; }
    }
}
