//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerInfo
    {
        public Nullable<int> CustomerID { get; set; }
        public string CompanyID { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusName { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> RegisterFrom { get; set; }
        public Nullable<System.DateTime> RegisterTo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> CustomerClassificationID { get; set; }
        public string CustomerClassification { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public string AccountType { get; set; }
        public string NationalID { get; set; }
        public string FINANCIAL_ACCOUNT_NUMBER { get; set; }
        public string Code { get; set; }
        public int UserID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string IdType { get; set; }
        public string TokenCode { get; set; }
        public Nullable<int> IsSubscribed { get; set; }
    }
}
