//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerReceiptPreference
    {
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> RECEIPT_TYPE_ID { get; set; }
    }
}
