//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerBenSearch
    {
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public string BENEFICIARY_NAME { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string BENEFICIARY_CODE { get; set; }
        public int UserID { get; set; }
    }
}
