//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerTagSearch
    {
        public int Token_ID { get; set; }
        public string TagNumberOpt { get; set; }
        public string TagSerialOpt { get; set; }
        public string TagNumber { get; set; }
        public string TagSerial { get; set; }
        public string TOKENNAME { get; set; }
        public string TOKENCODE { get; set; }
        public int DepotCentreID { get; set; }
        public int TOKEN_STATUS_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public int BENEFICIARY_ID { get; set; }
        public int CustomerTypeID { get; set; }
        public int WORK_ORDER_ID { get; set; }
        public int WORK_ORDER_TYPE_ID { get; set; }
        public int WORK_ORDER_REASON_ID { get; set; }
        public int VehicleYear { get; set; }
        public int FUEL_INLET { get; set; }
        public string BenefiicaryCode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string BenefiicaryName { get; set; }
        public string CustomerTypeAR { get; set; }
        public string CustomerType { get; set; }
        public string VehiclePlate { get; set; }
        public string VEHICLEMAKE { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleColor { get; set; }
        public string Emirate { get; set; }
        public string WorkOrderReason { get; set; }
        public string RFIDTYPEAR { get; set; }
        public string RFIDTYPEEN { get; set; }
        public string VehicleCategory { get; set; }
    }
}
