//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerStatusHistory
    {
        public int Customer_ID { get; set; }
        public Nullable<int> CUSTOMER_STATUS_ID { get; set; }
        public string EN_CUSTOMER_STATUS { get; set; }
        public Nullable<int> CUSTOMER_STATUS_REASON_ID { get; set; }
        public string Customer_STATUS_REASON_ENNAME { get; set; }
        public Nullable<System.DateTime> STATUS_CHANGE_DATE_TIME { get; set; }
        public string CODE { get; set; }
        public string USER_NAME { get; set; }
        public string AR_CUSTOMER_STATUS { get; set; }
        public string Customer_STATUS_REASON_ARNAME { get; set; }
    }
}
