//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerCardSearch
    {
        public string PersonalizationRequestNumber { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string CustomerName { get; set; }
        public string BeneficiaryName { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public string CustomerType { get; set; }
        public string CustomerTypeAR { get; set; }
        public string RecipientIdentityType { get; set; }
        public string RecipientIdentityTypeAR { get; set; }
        public Nullable<int> RecipientIdentityID { get; set; }
        public string IDENTITY_NUMBER { get; set; }
        public int PersonalizationOrderID { get; set; }
        public string CustomerCode { get; set; }
        public string BeneficiaryCode { get; set; }
        public string TokenCode { get; set; }
        public string TokenType { get; set; }
        public string TokenTypeAR { get; set; }
        public int ROW_NUM { get; set; }
    }
}
