//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerBeneficiaryResult
    {
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public string BENEFICIARY_NAME { get; set; }
        public string MOBILE { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public string STATUS_NAME { get; set; }
        public string NATIONALITY_NAME { get; set; }
        public Nullable<int> NATIONALILTY_ID { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<System.DateTime> REGISTRATION_DATE { get; set; }
        public Nullable<System.DateTime> REGISTER_FROM_DATE { get; set; }
        public Nullable<System.DateTime> REGISTER_TO_DATE { get; set; }
        public string CUSTOMER_GROUP { get; set; }
        public Nullable<int> IS_VIP { get; set; }
        public string BENEFICIARY_CODE { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public int UserID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string IdNumber { get; set; }
    }
}
