//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerBillingSearch
    {
        public int CUSTOMER_ID { get; set; }
        public int INVOICE_ID { get; set; }
        public Nullable<System.DateTime> BILLING_DATE { get; set; }
        public System.DateTime DUE_DATE { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public Nullable<System.DateTime> DATE_FROM { get; set; }
        public Nullable<System.DateTime> DATE_TO { get; set; }
        public string BILLING_PERIOD { get; set; }
        public int STATUS_ID { get; set; }
        public string STATUS_NAME { get; set; }
        public Nullable<decimal> TOTAL_TRANSACTION_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_ADJUSTMENT { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public string STATUS_NAME_ar { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    }
}
