//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerGroup
    {
        public int CUSTOMER_ID { get; set; }
        public int GROUP_ID { get; set; }
        public string EN_GROUP_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public short IS_ACTIVE { get; set; }
        public string AR_GROUP_NAME { get; set; }
        public Nullable<long> CostCenterID { get; set; }
    }
}
