//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTCustomerPayment
    {
        public Nullable<int> PAYMENT_ID { get; set; }
        public int CUSTOMER_ID { get; set; }
        public Nullable<int> PAYMENT_TYPE_ID { get; set; }
        public Nullable<int> INVOICE_ID { get; set; }
        public Nullable<int> PAYMENT_METHOD_ID { get; set; }
        public Nullable<int> IS_ACTIVE { get; set; }
        public decimal INITIAL_BALANCE { get; set; }
        public decimal TRANSACTION_AMOUNT { get; set; }
        public decimal FINAL_BALANCE { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
        public string REMARKS { get; set; }
        public string PAYMENT_DOCUMENT_REF { get; set; }
        public string AUTHORIZATION_CODE { get; set; }
        public string EN_PAYMENT_TYPE { get; set; }
        public string AR_PAYMENT_TYPE { get; set; }
        public string RESPONSIBLE_USER { get; set; }
        public string LOCATION_NAME { get; set; }
    }
}
