//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTDriverCard
    {
        public Nullable<int> TOKEN_ID { get; set; }
        public string TOKEN_NAME { get; set; }
        public string TOKEN_SERIAL { get; set; }
        public Nullable<System.DateTime> REGISTERATION_DATE { get; set; }
        public string TOKEN_STATUS_NAME { get; set; }
        public string TOKEN_CODE { get; set; }
        public Nullable<int> TOKEN_STATUS_ID { get; set; }
        public string TOKEN_STATUS_NAME_AR { get; set; }
    }
}
