//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTEmployeeIdentityCard
    {
        public Nullable<int> P_TOKEN_ID { get; set; }
        public Nullable<int> P_PERSONALIZATION_NUMBER { get; set; }
        public Nullable<int> P_PERSONALIZATION_STATUS_ID { get; set; }
        public Nullable<int> P_CARD_CENTER_ID { get; set; }
        public Nullable<System.DateTime> P_APPOINTMENT_DATE { get; set; }
        public Nullable<int> P_PRSNLIZTION_ORDR_TYP_ID { get; set; }
        public Nullable<int> P_PERSONALIZATION_REASON_ID { get; set; }
        public Nullable<int> P_EMPLOYEE_ID { get; set; }
        public Nullable<int> P_IDENTIFICATION_TYPE_ID { get; set; }
        public string P_IDENTITY_NUMBER { get; set; }
        public Nullable<int> P_CUSTOMER_ID { get; set; }
        public Nullable<System.DateTime> P_Last_updated_DATE { get; set; }
        public Nullable<int> P_Location_ID { get; set; }
        public Nullable<int> P_User_ID { get; set; }
    }
}
