//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTERPEmployee
    {
        public int EmployeeNumber { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeRole { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string LocationDepartment { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string NationalID { get; set; }
        public Nullable<long> EmployeePhone { get; set; }
        public string EmployeeMobile { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<int> LOCATION_ID { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
    }
}
