//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTFamilySegmentDTO
    {
        public int RuleID { get; set; }
        public int FamilyID { get; set; }
        public bool IsFirstVehicleOnly { get; set; }
        public bool IsActive { get; set; }
    }
}
