//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTGetVehicleInfo
    {
        public int VehicleEmirateId { get; set; }
        public string Color { get; set; }
        public string Category { get; set; }
        public int MakeId { get; set; }
        public string ModelName { get; set; }
        public string Year { get; set; }
        public string ChassisNumber { get; set; }
        public string TrafficNumber { get; set; }
        public Nullable<int> CC { get; set; }
        public Nullable<int> FuelInlet { get; set; }
        public Nullable<int> FuelCapacity { get; set; }
        public string Plate { get; set; }
        public string MakeName { get; set; }
        public int ModelId { get; set; }
        public int YearId { get; set; }
    }
}
