//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTInventoryReason
    {
        public Nullable<int> STATUS_REASON_ID { get; set; }
        public string EN_Name { get; set; }
        public string Ar_Name { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public string Status { get; set; }
    }
}
