//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTLocation
    {
        public Nullable<int> AddressID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> LocationTypeID { get; set; }
        public short IsActive { get; set; }
        public string LocationName { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
    }
}
