//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTMappedDriver
    {
        public int DRIVER_CARD_ID { get; set; }
        public string DriverCardCode { get; set; }
        public string DriverCardName { get; set; }
        public int TOKEN_ID { get; set; }
    }
}
