//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTMapCustomer
    {
        public int CUSTOMER_ID { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_STATUS { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public string BENEFICIARY_CODE { get; set; }
        public string BENEFICIARY_NAME { get; set; }
        public string BENEFICIARY_STATUS { get; set; }
        public Nullable<int> TOKEN_ID { get; set; }
        public string TOKEN_CODE { get; set; }
        public string TOKEN_NAME { get; set; }
        public string TOKEN_STATUS { get; set; }
        public Nullable<int> STATUS_ID { get; set; }
        public string CUSTOMER_STATUS_AR { get; set; }
        public Nullable<int> BENEFICIARY_STATUS_ID { get; set; }
        public string BENEFICIARY_STATUS_AR { get; set; }
        public Nullable<int> TOKEN_STATUS_ID { get; set; }
        public string TOKEN_STATUS_AR { get; set; }
        public Nullable<int> TOKEN_TYPE_ID { get; set; }
        public string TOKEN_TYPE_NAME_AR { get; set; }
        public string TOKEN_TYPE_NAME { get; set; }
        public string CUSTOMER_TYPE_NAME_AR { get; set; }
        public string CUSTOMER_TYPE_NAME { get; set; }
        public Nullable<int> CUSTOMER_TYPE_ID { get; set; }
        public Nullable<int> IS_DEFAULT_BENEFICIARY { get; set; }
    }
}
