//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTMapTokenToRule
    {
        public int RuleID { get; set; }
        public int LastUpdatedUserID { get; set; }
        public int LastUpdatedLocationID { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
