//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTOnlineDifferentialPricingDTO
    {
        public int RuleID { get; set; }
        public string RuleName { get; set; }
        public string Description { get; set; }
        public short IsRuleDisabled { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public short IsActive { get; set; }
        public int LastUpdatedUSerID { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int LastUpdatedLocationID { get; set; }
    }
}
