//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTOrderCancellation
    {
        public int OrderID { get; set; }
        public int TokenStatusID { get; set; }
        public int ServiceTypeID { get; set; }
        public string TokenStatusENName { get; set; }
        public string TokenStatusARName { get; set; }
        public string ServcieTypeName { get; set; }
        public Nullable<double> FeeAmount { get; set; }
    }
}
