//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTPersonalizationOrderSearch
    {
        public string PersonalizationRequestNumber { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string BeneficiaryCode { get; set; }
        public string BeneficiaryName { get; set; }
        public Nullable<int> PERSONALIZATION_ORDER_TYPE_ID { get; set; }
        public string OrderTypeName { get; set; }
        public string OrderTypeNameAR { get; set; }
        public Nullable<int> PERSONALIZATION_STATUS_ID { get; set; }
        public string OrderStatusName { get; set; }
        public string OrderStatusNameAR { get; set; }
        public Nullable<int> CARD_CENTER_ID { get; set; }
        public string CardCenterName { get; set; }
        public Nullable<int> PRINTING_STATUS_ID { get; set; }
        public string PrintingStatus { get; set; }
        public string PrintingStatusAR { get; set; }
        public string SERIAL { get; set; }
        public string PrinterName { get; set; }
        public Nullable<System.DateTime> PrintingDate { get; set; }
        public string REMARK { get; set; }
        public int PersonalizationOrderID { get; set; }
    }
}
