//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTPersonalizedData
    {
        public Nullable<int> TOKEN_ID { get; set; }
        public string CardSerial { get; set; }
        public short IS_VIP { get; set; }
        public Nullable<int> PRINTER_ID { get; set; }
        public Nullable<int> CARD_CENTER_ID { get; set; }
        public Nullable<int> TOKEN_STATUS_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public string BeneficiaryCode { get; set; }
        public string BeneficiaryName { get; set; }
        public Nullable<int> CUSTOMER_TYPE_ID { get; set; }
        public string CustomerType { get; set; }
        public string CustomerTypeAr { get; set; }
        public string TOKEN_CODE { get; set; }
        public string TokenName { get; set; }
    }
}
