//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTPersonalizationOrder
    {
        public int PERSONALIZATION_ORDER_ID { get; set; }
        public string PERSONALIZATION_NUMBER { get; set; }
        public Nullable<int> PERSONALIZATION_STATUS_ID { get; set; }
        public Nullable<int> CARD_CENTER_ID { get; set; }
        public Nullable<System.DateTime> APPOINTMENT_DATE_TIME { get; set; }
        public Nullable<int> PERSONALIZATION_ORDER_TYPE_ID { get; set; }
        public Nullable<int> PERSONALIZATION_REASON_ID { get; set; }
        public Nullable<int> IDENTIFICATION_TYPE_ID { get; set; }
        public string IDENTITY_NUMBER { get; set; }
        public Nullable<int> PRINTER_ID { get; set; }
        public Nullable<System.DateTime> ACTUAL_SERVICE_DATE_TIME { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public int PASSED_QUALITY_TEST { get; set; }
        public int IS_ACTIVE { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<int> LAST_LOCATION_ID { get; set; }
    }
}
