//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTPersonalizationOrderSearchInput
    {
        public string PersonalizationRequestNumber { get; set; }
        public Nullable<System.DateTime> AppointmentFrom { get; set; }
        public Nullable<System.DateTime> AppointmentTo { get; set; }
        public string CustomerCode { get; set; }
        public string BeneficiaryCode { get; set; }
        public Nullable<int> OrderTypeID { get; set; }
        public Nullable<int> OrderStatusID { get; set; }
        public Nullable<int> CardCenterID { get; set; }
        public Nullable<int> PrintingStatusID { get; set; }
        public string CardSerial { get; set; }
        public Nullable<System.DateTime> PrintingDateFrom { get; set; }
        public Nullable<System.DateTime> PrintingDateTo { get; set; }
        public Nullable<int> PersonalizationOrderID { get; set; }
        public int PageNo { get; set; }
        public int PageSize { get; set; }
    }
}
