//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTProductCategory
    {
        public Nullable<int> PRODUCT_CATEGORY_ID { get; set; }
        public string EN_NAME { get; set; }
        public string AR_NAME { get; set; }
        public Nullable<int> IS_PRODUCT_RESTRICTION { get; set; }
        public Nullable<int> IS_PER_TRANSACTION_LIMIT { get; set; }
        public Nullable<int> IS_TRANSACTION_FREQUENCY { get; set; }
        public Nullable<int> IS_AMOUNT_RESTRICTION { get; set; }
        public Nullable<int> IS_ACTIVE { get; set; }
        public Nullable<int> IS_QUANTITY_RESTRICTION { get; set; }
    }
}
