//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTPrintReceiptData
    {
        public string ADNOC_TRN_NO { get; set; }
        public string CUSTOMER_NO { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<System.DateTime> TRANS_DATE_TIME { get; set; }
        public string LOCATION_NAME { get; set; }
        public string REMARKS { get; set; }
        public string V_ADDRESS { get; set; }
        public string TRN { get; set; }
    }
}
