//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTProductSegmentDTO
    {
        public int RuleID { get; set; }
        public int ProductID { get; set; }
        public int StationID { get; set; }
        public System.DateTime FromHour { get; set; }
        public System.DateTime ToHour { get; set; }
        public int UpliftDiscount { get; set; }
        public short IsActive { get; set; }
    }
}
