//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTProductEOMSegmentDTO
    {
        public int RuleID { get; set; }
        public int ProductID { get; set; }
        public int AcountQuota { get; set; }
        public int TokenQuota { get; set; }
        public int TrxPerMonth { get; set; }
        public int UpliftDiscount { get; set; }
        public short IsActive { get; set; }
    }
}
