//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTProductServiceBillingFreq
    {
        public int BILLING_FREQ_ID { get; set; }
        public string BILLING_FREQUENCY { get; set; }
        public string BILLING_TYPE { get; set; }
        public int BILLING_TYPE_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
