//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTQualityAssurance
    {
        public string CardSerial { get; set; }
        public Nullable<short> QualityPassed { get; set; }
        public string TokenCode { get; set; }
        public string FailureReason { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
