//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRestrictionSummary
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> RESTRICTION_GROUP_ID { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
    }
}
