//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRequest
    {
        public string AR_RequestType { get; set; }
        public string EN_RequestType { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
        public Nullable<int> REQUEST_ID { get; set; }
        public Nullable<int> REQUEST_TYPE_ID { get; set; }
        public Nullable<int> REQUEST_STATUS_ID { get; set; }
        public Nullable<int> REQUESTER_USER_ID { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public Nullable<int> TOKEN_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<int> IS_ACTIVE { get; set; }
        public string Code { get; set; }
        public Nullable<int> LAST_LOCATION_ID { get; set; }
    }
}
