//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRequestCustomerAddress
    {
        public string ARAreaName { get; set; }
        public string ARCityName { get; set; }
        public string ARCountryName { get; set; }
        public string POST_CODE { get; set; }
        public string DETAILED_ADDRESS { get; set; }
        public string FAX { get; set; }
        public string PHONE_NUMBER { get; set; }
        public Nullable<int> IS_ACTIVE { get; set; }
        public Nullable<int> ADDRESS_ID { get; set; }
        public Nullable<int> area_id { get; set; }
        public Nullable<int> City_id { get; set; }
        public Nullable<int> Country_id { get; set; }
        public string ENCityName { get; set; }
        public string ENAreaName { get; set; }
        public string ENCountryName { get; set; }
    }
}
