//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRestrictionGroupProfile
    {
        public Nullable<int> RESTRICTION_GROUP_ID { get; set; }
        public string NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<short> IS_SYSTEM_DEFINED_GROUP { get; set; }
        public Nullable<int> CONSECUTIVE_USAGE_RESTRICTION { get; set; }
        public Nullable<short> IS_RESTRICTED_IN_HOLIDAY { get; set; }
        public Nullable<short> IS_REQUIRE_ODOMETER_INPUT { get; set; }
        public Nullable<short> IS_REQUIRE_DRIVER_CARD { get; set; }
        public Nullable<short> CAN_BUY_DRY_STOCK { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> CAN_USE_ADNOC_SERVICE { get; set; }
    }
}
