//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRequestAccountManager
    {
        public Nullable<int> user_id { get; set; }
        public Nullable<int> LastLocationID { get; set; }
        public Nullable<int> LastUserID { get; set; }
        public Nullable<int> AccountManagerID { get; set; }
        public Nullable<int> isActive { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Name { get; set; }
    }
}
