//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRequestCustomer
    {
        public Nullable<int> RequestCustomerId { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> BasicAddressId { get; set; }
        public Nullable<int> BillingAddressId { get; set; }
        public Nullable<int> ShippingAddressId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> IdentificationTypeID { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public string Name { get; set; }
        public string NationalID { get; set; }
        public string ReceiptPreference { get; set; }
        public string IdentificationID { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> FamilyID { get; set; }
        public Nullable<int> FinancialAccountTypeID { get; set; }
        public string FinancialAccountNo { get; set; }
        public Nullable<int> AccountManagerID { get; set; }
        public Nullable<int> FinancialContactID { get; set; }
        public Nullable<int> OperationalContactID { get; set; }
        public Nullable<int> NotificationThreshold { get; set; }
        public Nullable<int> SuspensionThreshold { get; set; }
        public Nullable<int> IsVIP { get; set; }
        public Nullable<int> NotificationLanguageID { get; set; }
        public Nullable<int> NotificationChannelID { get; set; }
        public Nullable<int> RequestSourceTypeID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<int> PaymentTerms { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public string CompanyID { get; set; }
        public Nullable<int> ClassificationId { get; set; }
        public Nullable<int> CardCentreID { get; set; }
        public Nullable<int> LastUserID { get; set; }
        public Nullable<int> LastLocationID { get; set; }
        public Nullable<int> BillingFrequencyID { get; set; }
        public Nullable<int> BillingFrequencyDayOrder { get; set; }
        public Nullable<int> EnableDefaultBeneficiary { get; set; }
        public string FinanialAccountType { get; set; }
        public Nullable<int> MonthlyVolumeID { get; set; }
        public Nullable<int> IsPremier { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public int IsEmployer { get; set; }
        public Nullable<int> CustBillFrequency { get; set; }
        public string ContractNumber { get; set; }
    }
}
