//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRestrictionGroupTrans
    {
        public int RESTRICTION_GROUP_ID { get; set; }
        public Nullable<decimal> MAXIMUM_TRANSACTION_AMOUNT { get; set; }
        public Nullable<int> WEEK_DAY_ID { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> PRODUCT_CATEGORY_ID { get; set; }
    }
}
