//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRequestWorkflowHistoryDTO
    {
        public string TokenName { get; set; }
        public string BeneficiaryName { get; set; }
        public string RequestNumber { get; set; }
        public string CustomerName { get; set; }
        public string RequestType { get; set; }
        public string RequestSource { get; set; }
        public string CurrentRequestStatus { get; set; }
        public int REQUEST_ID { get; set; }
    }
}
