//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRestrictionGroupInfo
    {
        public Nullable<int> RS_GRP_ID { get; set; }
        public string RS_GRP_NAME { get; set; }
        public string RS_GRP_DESCRIPTION { get; set; }
        public Nullable<short> RS_GRP_IS_SYS_DEF_GRP { get; set; }
        public Nullable<int> RS_GRP_CONSEC_USG_RS { get; set; }
        public Nullable<short> RS_GRP_IS_RS_IN_HILIDAY { get; set; }
        public Nullable<short> RS_GRP_IS_REQ_ODOMTR_INPUT { get; set; }
        public Nullable<short> RS_GRP_IS_REQ_DRIVER_CARD { get; set; }
        public Nullable<short> RS_GRP_CAN_BUY_DRY_STOCK { get; set; }
        public Nullable<short> RS_GRP_IS_ACTIVE { get; set; }
        public Nullable<int> RS_GRP_AMOUNT_TIME_FREQ_ID { get; set; }
        public Nullable<int> RS_GRP_AMOUNT_ALLOWED { get; set; }
        public string TIME_FREQ_NAME { get; set; }
        public Nullable<short> TIME_FREQ_IS_ACTIVE { get; set; }
        public Nullable<int> RS_GRP_PRODUCT_ID { get; set; }
        public string RS_GRP_PRODUCT { get; set; }
        public Nullable<int> RS_GRP_STATION_ID { get; set; }
        public string RS_GRP_STATION_NAME { get; set; }
        public Nullable<int> RS_GRP_TRANS_NO_NO_OF_DAYS { get; set; }
        public Nullable<int> RS_GRP_TRANS_NO_NO_OF_TRANS { get; set; }
        public Nullable<int> RS_GRP_WKDY_ID { get; set; }
        public string RS_GRP_WKDY_NAME { get; set; }
    }
}
