//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRequestDocument
    {
        public Nullable<int> RequestDocumentId { get; set; }
        public Nullable<int> IsRequired { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> RequestTypeId { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string EnName { get; set; }
        public string ArName { get; set; }
        public string EN_DESCRIPTION { get; set; }
        public string AR_DESCRIPTION { get; set; }
    }
}
