//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTReceiptDetails
    {
        public string NAME { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string VAT_CODE { get; set; }
        public Nullable<decimal> VAT_RATE { get; set; }
        public Nullable<decimal> VAT_AMOUNT { get; set; }
        public string VAT_INVOICE_NUMBER { get; set; }
    }
}
