//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRestrictionGroup
    {
        public Nullable<int> RESTRICTION_GROUP_ID { get; set; }
        public string RS_GRP_NAME { get; set; }
        public string RS_GRP_DESCRIPTION { get; set; }
        public short RS_GRP_IS_SYS_DEF_GRP { get; set; }
        public Nullable<int> CONSECUTIVE_USAGE_RESTRICTION { get; set; }
        public Nullable<short> IS_RESTRICTED_IN_HOLIDAY { get; set; }
        public Nullable<short> IS_REQUIRE_ODOMETER_INPUT { get; set; }
        public Nullable<short> IS_REQUIRE_DRIVER_CARD { get; set; }
        public Nullable<short> CAN_BUY_DRY_STOCK { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<int> TIME_FREQUENCY_ID { get; set; }
        public Nullable<int> ALLOWED_AMOUNT { get; set; }
        public string EN_NAME { get; set; }
        public Nullable<int> IS_ACTIVE_1 { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public string EN_NAME_1 { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public string EN_NAME_2 { get; set; }
        public Nullable<int> NUMBER_OF_DAYS { get; set; }
        public Nullable<int> NUMBER_OF_TRANSACTIONS { get; set; }
        public Nullable<int> WEEK_DAY_ID { get; set; }
        public string EN_NAME_3 { get; set; }
        public string RS_AMOUNT { get; set; }
        public string RS_QUANTITY { get; set; }
        public string RS_PRODUCT { get; set; }
        public string RS_TRANSNO { get; set; }
        public string RS_TRANS { get; set; }
        public string RS_WEEKDAY { get; set; }
        public string RS_STATION { get; set; }
        public Nullable<short> CAN_USE_ADNOC_SERVICE { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string RS_TIME { get; set; }
    }
}
