//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRequestServiceFee
    {
        public int RequestID { get; set; }
        public Nullable<int> Service_Fee_ID { get; set; }
        public int ServiceID { get; set; }
        public Nullable<int> Customer_Status_ID { get; set; }
        public Nullable<int> Customer_Type_ID { get; set; }
        public Nullable<int> Account_Type_ID { get; set; }
        public Nullable<int> Classification_ID { get; set; }
        public Nullable<int> ISPremier { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public decimal Fee { get; set; }
        public int IsActive { get; set; }
        public string ServiceName_en { get; set; }
        public string CustomerStatus_en { get; set; }
        public string CustomerType_en { get; set; }
        public string AccountType_en { get; set; }
        public string ClassificationName_en { get; set; }
        public string LocationName_en { get; set; }
        public string AccountType_ar { get; set; }
        public string CustomerStatus_ar { get; set; }
        public string LocationName_ar { get; set; }
        public string ServiceName_ar { get; set; }
        public string CustomerType_ar { get; set; }
        public string ClassificationName_ar { get; set; }
    }
}
