//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRequestAccountClosure
    {
        public Nullable<int> RequestCustomerId { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string CompanyID { get; set; }
        public Nullable<int> BasicAddressId { get; set; }
        public Nullable<int> BillingAddressId { get; set; }
        public Nullable<int> ShippingAddressId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
        public Nullable<int> CustomerTypeID { get; set; }
        public Nullable<int> AccountTypeID { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string Name { get; set; }
        public Nullable<int> ClassificationId { get; set; }
        public string Classification { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string AccountStatus { get; set; }
        public decimal AccountBalance { get; set; }
        public string Nationality { get; set; }
        public string identificationtype { get; set; }
        public string NationalID { get; set; }
    }
}
