//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTRQSTAttachment
    {
        public string FILEEXTENSION { get; set; }
        public Nullable<int> ATTACHMENT_ID { get; set; }
        public Nullable<int> REQUESTDOCUMENTID { get; set; }
        public byte[] ATTACHMENT { get; set; }
        public Nullable<int> LastLocationID { get; set; }
        public Nullable<int> LastUserID { get; set; }
        public Nullable<int> REQUEST_ID { get; set; }
    }
}
