//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTSearchTokensForRuleResultDTO
    {
        public int RuleID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string BeneficiaryCode { get; set; }
        public string BeneficiaryName { get; set; }
        public string TokenCode { get; set; }
        public string TokenName { get; set; }
        public int TokenTypeID { get; set; }
        public string TokenType { get; set; }
        public string TokenSerial { get; set; }
        public int OnlineDPID { get; set; }
        public string OnlineDPName { get; set; }
        public int EOMDPID { get; set; }
        public string EOMDPName { get; set; }
    }
}
