//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTSearchPendingRequestResult
    {
        public Nullable<int> RequestId { get; set; }
        public Nullable<int> RequestTypeID { get; set; }
        public Nullable<int> RequestStatusId { get; set; }
        public Nullable<int> RequesterUserId { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<int> LastUpdatedUserId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string RequestType { get; set; }
        public string RequestStatus { get; set; }
        public string CustomerName { get; set; }
        public string BeneficiaryName { get; set; }
        public string TokenName { get; set; }
        public string Remarks { get; set; }
        public string RequestCode { get; set; }
        public int RequestActionID { get; set; }
        public string RequestAction { get; set; }
        public string RequestOriginatorUserName { get; set; }
        public string LastUpdatedUserName { get; set; }
        public Nullable<int> WF_Instance_Id { get; set; }
        public string EscalationStatus { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<int> Row_Num { get; set; }
    }
}
