//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTSearchDPRulesDTO
    {
        public string RuleName { get; set; }
        public int RuleTypeID { get; set; }
        public int ProductID { get; set; }
        public int StationID { get; set; }
    }
}
