//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTSearchDPRulesResultDTO
    {
        public string RuleName { get; set; }
        public int RuleID { get; set; }
        public string Description { get; set; }
        public int RuleTypeID { get; set; }
        public string RuleType { get; set; }
        public System.DateTime ValidFromDate { get; set; }
        public System.DateTime ValidToDate { get; set; }
    }
}
