//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTSearchTokenToDeliver
    {
        public string TokenCode { get; set; }
        public string TokenName { get; set; }
        public Nullable<int> TokenTypeID { get; set; }
        public string TokenSerial { get; set; }
        public Nullable<int> BeneficiaryID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string BeneficiaryName { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> PageNumber { get; set; }
        public Nullable<int> PageSize { get; set; }
        public string BeneficiaryCode { get; set; }
    }
}
