//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTSearchTokenIssuanceResult
    {
        public string TokenName { get; set; }
        public string CustomerCode { get; set; }
        public string MobileNumber { get; set; }
        public string BeneficiaryCode { get; set; }
        public string BeneficiaryName { get; set; }
        public Nullable<int> CustomerStatusID { get; set; }
        public string TokenSerial { get; set; }
        public string TokenCode { get; set; }
        public string CustomerName { get; set; }
        public string CompanyRegistrationID { get; set; }
        public Nullable<int> ClassificationID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string FinancialAccountNumber { get; set; }
        public Nullable<int> EmployeeNumber { get; set; }
        public string TokenType { get; set; }
        public string TokenStatus { get; set; }
        public Nullable<int> TokenTypeID { get; set; }
        public Nullable<int> TokenID { get; set; }
    }
}
