//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTTokenAccountSearch
    {
        public Nullable<int> TOKEN_ID { get; set; }
        public string TOKEN_NAME { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public string BENEFICIARY_NAME { get; set; }
        public Nullable<int> RESTRICTION_GROUP_ID { get; set; }
        public string RESTRICTION_GROUP_NAME { get; set; }
        public Nullable<int> TOKEN_STATUS_ID { get; set; }
        public string TOKEN_STATUS_EN_NAME { get; set; }
        public Nullable<System.DateTime> REGISTER_FROM_DATE { get; set; }
        public Nullable<System.DateTime> REGISTER_TO_DATE { get; set; }
        public Nullable<System.DateTime> REGISTERATION_DATE { get; set; }
        public Nullable<int> TOKEN_TYPE_ID { get; set; }
        public string TOKEN_TYPE_EN_NAME { get; set; }
        public string SERIAL { get; set; }
        public string TOKEN_STATUS_AR_NAME { get; set; }
        public string TOKEN_TYPE_AR_NAME { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string EMPLOYEE_NO { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string IdNumber { get; set; }
        public string TOKEN_CODE { get; set; }
        public string CustomerName { get; set; }
        public string VehicleNo { get; set; }
    }
}
