//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTTokenRestrictionInfo
    {
        public Nullable<int> CUSTOMERID { get; set; }
        public Nullable<int> BENEFICIARYID { get; set; }
        public Nullable<int> TOKENID { get; set; }
        public string TOKENNAME { get; set; }
        public Nullable<int> TOKENTYPEID { get; set; }
        public Nullable<int> RESTRICTIONGROUPID { get; set; }
        public string TOKENTYPE { get; set; }
        public string RESTRICTIONGROUPNAME { get; set; }
        public string TokenTypeAR { get; set; }
    }
}
