//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTTokenRestriction
    {
        public Nullable<int> CUSTOMERID { get; set; }
        public Nullable<int> BENEFICIARYID { get; set; }
        public Nullable<int> TOKENID { get; set; }
        public string TOKENNAME { get; set; }
        public Nullable<int> TOKENTYPEID { get; set; }
        public string TOKENTYPE { get; set; }
        public Nullable<int> RESTRICTIONGROUPID { get; set; }
        public string RESTRICTIONGROUPNAME { get; set; }
        public Nullable<short> IS_SYSTEM_DEFINED_GROUP { get; set; }
        public Nullable<int> CONSECUTIVE_USAGE_RESTRICTION { get; set; }
        public Nullable<short> IS_RESTRICTED_IN_HOLIDAY { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<short> IS_REQUIRE_ODOMETER_INPUT { get; set; }
        public Nullable<short> IS_REQUIRE_DRIVER_CARD { get; set; }
        public Nullable<short> CAN_BUY_DRY_STOCK { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public string RS_AMOUNT { get; set; }
        public string RS_PRODUCT { get; set; }
        public string RS_QUANTITY { get; set; }
        public string RS_TRANSNO { get; set; }
        public string RS_TRANS { get; set; }
        public string RS_STATION { get; set; }
        public string RS_WEEKDAY { get; set; }
        public Nullable<short> CAN_USE_ADNOC_SERVICE { get; set; }
        public int LastLocationID { get; set; }
        public string RS_TIME { get; set; }
    }
}
