//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTTokenStatusHistory
    {
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public Nullable<int> TOKEN_ID { get; set; }
        public Nullable<int> TOKEN_STATUS_ID { get; set; }
        public string TOKEN_STATUS_NAME { get; set; }
        public Nullable<int> TOKEN_STATUS_REASON_ID { get; set; }
        public string TOKEN_STATUS_REASON_NAME { get; set; }
        public Nullable<System.DateTime> STATUS_CHANGE_DATE_TIME { get; set; }
        public string code { get; set; }
        public string TOKEN_STATUS_NAME_AR { get; set; }
        public string token_STATUS_REASON_NAME_AR { get; set; }
        public string USER_NAME { get; set; }
    }
}
