//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTTransactionEXTVoucherMapSA
    {
        public string EXT_VOUCHER_NO { get; set; }
        public string VOUCHER_SERIAL_NUMBER { get; set; }
        public string VAT_INVOICE_NO { get; set; }
        public string ACTION { get; set; }
        public Nullable<System.DateTime> OPERATION_DATE { get; set; }
        public string LOCATION_NAME { get; set; }
        public string RESPONSIBLE_USER { get; set; }
    }
}
