//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTTransactionReversal
    {
        public string TRANSACTION_TYPE { get; set; }
        public string VAT_INVOICE_NO { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string BENEFICIARY_CODE { get; set; }
        public string BENEFICIARY_NAME { get; set; }
        public string TOKEN_TYPE { get; set; }
        public string TOKEN_SERIAL { get; set; }
        public string STATION_NAME { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string AUTHORIZATION_CODE { get; set; }
        public Nullable<int> RECEIPT_ID { get; set; }
        public Nullable<int> REVERSED_TRANSACTION_ID { get; set; }
        public Nullable<int> REVERSED_TRANSACTION_DETAIL_ID { get; set; }
        public Nullable<int> TRANSACTION_ID { get; set; }
        public Nullable<int> TRANSACTION_DETAIL_ID { get; set; }
        public Nullable<short> IS_PAYMENT { get; set; }
        public Nullable<decimal> TRANSACTION_AMOUNT { get; set; }
        public Nullable<decimal> VAT_AMOUNT { get; set; }
        public Nullable<System.DateTime> TRANSACTION_DATE { get; set; }
        public Nullable<short> IS_PREMIUM_SERVICE { get; set; }
    }
}
