//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTTransactionReversalSearch
    {
        public string AUTHORIZATION_CODE { get; set; }
        public string BENEFICIARY_CODE { get; set; }
        public string BENEFICIARY_NAME { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> RECEIPT_ID { get; set; }
        public Nullable<int> STATION_ID { get; set; }
        public Nullable<int> TOKEN_TYPE_ID { get; set; }
        public string TOKEN_SERIAL { get; set; }
        public Nullable<int> TRANSACTION_TYPE_ID { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string VAT_INV_NUM { get; set; }
        public Nullable<short> IsPremiumService { get; set; }
    }
}
