//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTUnmappedTokenSearch
    {
        public string TOKEN_NAME { get; set; }
        public string BENEFICIARY_NAME { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public Nullable<int> TOKEN_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
    }
}
