//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTVehicleRegister
    {
        public Nullable<int> VEHICLE_REGISTER_ID { get; set; }
        public Nullable<int> MAKE_ID { get; set; }
        public Nullable<int> MODEL_ID { get; set; }
        public string MAKE_NAME_EN { get; set; }
        public string MODEL_NAME_AR { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<int> CC { get; set; }
        public Nullable<decimal> FUEL_CAPACITY { get; set; }
        public Nullable<int> FUEL_INLET { get; set; }
        public string Inventory_Unit_Type_NAME { get; set; }
        public string Inventory_Unit_Type_NAME_ar { get; set; }
        public string MAKE_NAME_AR { get; set; }
        public string MODEL_NAME_EN { get; set; }
    }
}
