//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTVehicleInfo
    {
        public string CHASSIS_NUMBER { get; set; }
        public Nullable<int> COLOR_ID { get; set; }
        public short IS_ACTIVE { get; set; }
        public string PLATE_COLOUR_ID { get; set; }
        public string PLATE_NUMBER { get; set; }
        public Nullable<int> STATE_ID { get; set; }
        public int VEHICLE_INFO_ID { get; set; }
        public int VEHICLE_REGISTER_ID { get; set; }
        public Nullable<int> VEHICLE_TYPE_ID { get; set; }
        public string VehicleColor { get; set; }
        public string VehiclStateName { get; set; }
        public string VehiclTypeName { get; set; }
        public string ENGINE_NUMBER { get; set; }
    }
}
