//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTVehicleMakeModel
    {
        public Nullable<int> VEHICLE_MAKE_ID { get; set; }
        public string Vehicle_Make_Name { get; set; }
        public Nullable<int> VEHICLE_MODEL_ID { get; set; }
        public string Vehicle_Model_Name { get; set; }
        public short model_is_active { get; set; }
        public string Vehicle_Make_Name_AR { get; set; }
        public string Vehicle_Model_Name_AR { get; set; }
    }
}
