//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTWorkFlowHistory
    {
        public Nullable<int> WFInstanceID { get; set; }
        public string Status { get; set; }
        public string AssignedTo { get; set; }
        public string User { get; set; }
        public string Action { get; set; }
        public string Remarks { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<int> HasHistoryData { get; set; }
    }
}
