//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTWorkOrderData
    {
        public string Tag_Serial { get; set; }
        public string TagNumber { get; set; }
        public string TagSerialOpt { get; set; }
        public string TagNumberOpt { get; set; }
        public Nullable<int> Token_ID { get; set; }
        public Nullable<int> WORK_ORDER_ID { get; set; }
        public Nullable<int> DepotCentreID { get; set; }
        public Nullable<int> NUMBER_OF_ACTIVE_TAGS { get; set; }
        public Nullable<int> USER_ID { get; set; }
    }
}
