//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTWorkOrderSearchResult
    {
        public string WORK_ORDER_NUMBER { get; set; }
        public string APPOINTMENT_DATE_TIME { get; set; }
        public string OrderStatusName { get; set; }
        public string OrderStatusNameAR { get; set; }
        public string DepotCenterName { get; set; }
        public string TagSerial { get; set; }
        public string TagNumber { get; set; }
        public string TagSerialOpt { get; set; }
        public string TagNumberOpt { get; set; }
        public string tokencode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string BenefiicaryCode { get; set; }
        public string BeneficiaryName { get; set; }
        public string OrderTypeName { get; set; }
        public string OrderTypeNameAR { get; set; }
        public string tokenname { get; set; }
        public Nullable<int> WORK_ORDER_TYPE_ID { get; set; }
        public Nullable<int> WORK_ORDER_STATUS_ID { get; set; }
        public Nullable<int> DepotCentreID { get; set; }
    }
}
