//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    
    public partial class CTWorkOrderRemovalData
    {
        public Nullable<int> Token_ID { get; set; }
        public Nullable<int> DepotCentreID { get; set; }
        public Nullable<int> WORK_ORDER_ID { get; set; }
        public Nullable<int> WORK_ORDER_TYPE_ID { get; set; }
        public Nullable<int> Reason { get; set; }
        public Nullable<int> ISTOKENPROFILETERMINATE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string Tag_Serial { get; set; }
        public string Tag_Number { get; set; }
        public string Tag_Serial_Opt { get; set; }
        public string Tag_Number_Opt { get; set; }
        public string Remarks { get; set; }
    }
}
