//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_ATTACHMENT
    {
        public int ATTACHMENT_ID { get; set; }
        public Nullable<int> REQUESTDOCUMENTID { get; set; }
        public byte[] ATTACHMENT { get; set; }
        public string FILEEXTENSION { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
