//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_ACCOUNT_TYPE
    {
        public CUSTOMER_ACCOUNT_TYPE()
        {
            this.CUSTOMER = new HashSet<CUSTOMER>();
        }
    
        public int CUSTOMER_ACCOUNT_TYPE_ID { get; set; }
        public string EN_CUSTOMER_ACCOUNT_TYPE { get; set; }
        public string AR_CUSTOMER_ACCOUNT_TYPE { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual ICollection<CUSTOMER> CUSTOMER { get; set; }
    }
}
