//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_STATUS
    {
        public CUSTOMER_STATUS()
        {
            this.CUSTOMER = new HashSet<CUSTOMER>();
            this.CUSTOMER_STATUS_REASON = new HashSet<CUSTOMER_STATUS_REASON>();
            this.CUSTOMER_STATUS_CHANGE_LOG = new HashSet<CUSTOMER_STATUS_CHANGE_LOG>();
        }
    
        public int CUSTOMER_STATUS_ID { get; set; }
        public string EN_CUSTOMER_STATUS { get; set; }
        public short IS_ACTIVE { get; set; }
        public string AR_CUSTOMER_STATUS { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual ICollection<CUSTOMER> CUSTOMER { get; set; }
        public virtual ICollection<CUSTOMER_STATUS_REASON> CUSTOMER_STATUS_REASON { get; set; }
        public virtual ICollection<CUSTOMER_STATUS_CHANGE_LOG> CUSTOMER_STATUS_CHANGE_LOG { get; set; }
    }
}
