//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public CUSTOMER()
        {
            this.BENEFICIARY_GROUP = new HashSet<BENEFICIARY_GROUP>();
            this.SMS_MESSAGE = new HashSet<SMS_MESSAGE>();
            this.CUSTOMER_PIN_LOG = new HashSet<CUSTOMER_PIN_LOG>();
            this.TOKEN = new HashSet<TOKEN>();
            this.RECEIPT_TYPE = new HashSet<RECEIPT_TYPE>();
            this.CUSTOMER_CONTACT = new HashSet<CUSTOMER_CONTACT>();
            this.CUSTOMER_PRODUCT_UPLIFT = new HashSet<CUSTOMER_PRODUCT_UPLIFT>();
            this.CUSTOMER_STATUS_CHANGE_LOG = new HashSet<CUSTOMER_STATUS_CHANGE_LOG>();
            this.CUSTOMER_ATTACHMENT = new HashSet<CUSTOMER_ATTACHMENT>();
            this.BENEFICIARies = new HashSet<BENEFICIARY>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public int CUSTOMER_TYPE_ID { get; set; }
        public Nullable<int> CLASSIFICATION_ID { get; set; }
        public int ACCOUNT_TYPE_ID { get; set; }
        public Nullable<int> NATIONALITY_ID { get; set; }
        public string NATIONAL_ID { get; set; }
        public Nullable<int> BASIC_ADDRESS_ID { get; set; }
        public Nullable<int> BILLING_ADDRESS_ID { get; set; }
        public Nullable<int> SHIPPING_ADDRESS_ID { get; set; }
        public Nullable<int> FAMILY_ID { get; set; }
        public Nullable<int> FINANCIAL_ACCOUNT_TYPE_ID { get; set; }
        public string FINANCIAL_ACCOUNT_NUMBER { get; set; }
        public Nullable<int> ACCOUNT_MANAGER_ID { get; set; }
        public Nullable<int> BILLING_FREQUENCY_ID { get; set; }
        public Nullable<decimal> NOTIFICATION_THRESHOLD { get; set; }
        public Nullable<decimal> SUSPPENSION_THRESHOLD { get; set; }
        public short IS_VIP { get; set; }
        public System.DateTime REGISTRATION_DATE { get; set; }
        public int STATUS_ID { get; set; }
        public Nullable<int> STATUS_REASON_ID { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public string PIN { get; set; }
        public int NOTIFICATION_LANGUAGE_ID { get; set; }
        public int NOTIFICATION_CHANNEL_ID { get; set; }
        public Nullable<int> REQUEST_SOURCE_TYPE_ID { get; set; }
        public string CARD_CENTER_ID { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<int> UNIT_ID { get; set; }
        public Nullable<int> BILLING_FREQUENCY_DAY_ORDER { get; set; }
        public Nullable<int> PAYEMENT_TERMS { get; set; }
        public Nullable<int> IDENTIFICATION_TYPE_ID { get; set; }
        public Nullable<int> STATUS_CHANGE_LOG_ID { get; set; }
        public string COMPANY_ID { get; set; }
        public Nullable<decimal> IS_PREMIER { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
        public string GENDER { get; set; }
        public Nullable<short> IS_LOYALITY_CUSTOMER { get; set; }
        public string TRN { get; set; }
        public Nullable<short> IS_VAT_EXEMPTED { get; set; }
        public string EXEMPTION_REASON { get; set; }
        public Nullable<short> ISBENEFICIARYIDNONUNIQUE { get; set; }
        public Nullable<decimal> CUSTOM_BILL_FREQUENCY { get; set; }
        public Nullable<short> IS_EMPLOYER { get; set; }
        public string CONTRACT_NUMBER { get; set; }
    
        public virtual ACCOUNT_MANAGER ACCOUNT_MANAGER { get; set; }
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual ADDRESS ADDRESS1 { get; set; }
        public virtual ADDRESS ADDRESS2 { get; set; }
        public virtual ICollection<BENEFICIARY_GROUP> BENEFICIARY_GROUP { get; set; }
        public virtual CUSTOMER_TYPE CUSTOMER_TYPE { get; set; }
        public virtual CUSTOMER_CLASSIFICATION CUSTOMER_CLASSIFICATION { get; set; }
        public virtual CUSTOMER_ACCOUNT_TYPE CUSTOMER_ACCOUNT_TYPE { get; set; }
        public virtual NATIONALITY NATIONALITY { get; set; }
        public virtual FINANCIAL_ACCOUNT_TYPE FINANCIAL_ACCOUNT_TYPE { get; set; }
        public virtual TIME_FREQUENCY TIME_FREQUENCY { get; set; }
        public virtual CUSTOMER_STATUS CUSTOMER_STATUS { get; set; }
        public virtual CUSTOMER_STATUS_REASON CUSTOMER_STATUS_REASON { get; set; }
        public virtual FAMILY FAMILY { get; set; }
        public virtual NOTIFICATION_CHANNEL NOTIFICATION_CHANNEL { get; set; }
        public virtual NOTIFICATION_LANGUAGE NOTIFICATION_LANGUAGE { get; set; }
        public virtual ICollection<SMS_MESSAGE> SMS_MESSAGE { get; set; }
        public virtual CUSTOMER_BALANCE CUSTOMER_BALANCE { get; set; }
        public virtual ICollection<CUSTOMER_PIN_LOG> CUSTOMER_PIN_LOG { get; set; }
        public virtual ICollection<TOKEN> TOKEN { get; set; }
        public virtual ICollection<RECEIPT_TYPE> RECEIPT_TYPE { get; set; }
        public virtual ICollection<CUSTOMER_CONTACT> CUSTOMER_CONTACT { get; set; }
        public virtual ICollection<CUSTOMER_PRODUCT_UPLIFT> CUSTOMER_PRODUCT_UPLIFT { get; set; }
        public virtual ICollection<CUSTOMER_STATUS_CHANGE_LOG> CUSTOMER_STATUS_CHANGE_LOG { get; set; }
        public virtual IDENTIFICATION_TYPE IDENTIFICATION_TYPE { get; set; }
        public virtual ICollection<CUSTOMER_ATTACHMENT> CUSTOMER_ATTACHMENT { get; set; }
        public virtual ICollection<BENEFICIARY> BENEFICIARies { get; set; }
        public virtual MONTH MONTH { get; set; }
    }
}
