//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMAIL_NOTIFICATION
    {
        public int EMAIL_NOTIFICATION_ID { get; set; }
        public string NOTIFICATION_SOURCE { get; set; }
        public string EMAIL_BODY { get; set; }
        public string EMAIL_SUBJECT { get; set; }
        public string EMAIL_RECEPIENTS { get; set; }
        public System.DateTime DATE_RECEIVED { get; set; }
        public Nullable<short> IS_SENT { get; set; }
        public Nullable<System.DateTime> DATE_PROCESSED { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<short> ENABLED_LIFE_TIME { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<decimal> LIFE_TIME { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
    
        public virtual LANGUAGE LANGUAGE { get; set; }
    }
}
