//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_CUSTOMER
    {
        public int CUSTOMER_ID { get; set; }
        public string CUSTOMER_NUMBER { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_CLASSIFICATION { get; set; }
        public Nullable<decimal> BILL_TO_ADDRESS_ID { get; set; }
        public Nullable<decimal> ORG_ID { get; set; }
        public string DEFAULT_PAYMENT_TERM { get; set; }
        public Nullable<System.DateTime> REGISTRATION_DATE { get; set; }
        public string CUST_STATUS { get; set; }
        public Nullable<decimal> CUSTOMER_CREDIT_LIMIT { get; set; }
        public string PRIMARY_CONTACT_NAME { get; set; }
        public string PRIMARY_CONTACT_PHONE { get; set; }
        public string CONTACT_JOB_TITLE { get; set; }
        public Nullable<decimal> SALES_PERSON_ID { get; set; }
        public string SALES_PERSON_NAME { get; set; }
        public string SALES_PERSON_TELEPHONE { get; set; }
        public string COUNTRY { get; set; }
        public string CITY { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string ADDRESS4 { get; set; }
        public string EMAIL { get; set; }
        public string PO_BOX { get; set; }
        public string CUSTOMER_TYPE { get; set; }
        public string FINANCIAL_ACCOUNT_NUMBER { get; set; }
        public string BILL_TO_ADDRESS { get; set; }
        public short IS_ACTIVE { get; set; }
        public string CUSTOMER_FAX { get; set; }
        public string BILL_TO_FAX { get; set; }
        public string BILL_TO_NUMBER { get; set; }
        public string TRN { get; set; }
        public string VAT_EXEMPTION { get; set; }
        public string EXEMPTION_REASON { get; set; }
        public string COMPANY_ID { get; set; }
        public string SITE_NUMBER { get; set; }
        public string SITE_NAME { get; set; }
        public string SITE_CLASSIFICATION { get; set; }
    }
}
