//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_GL_ACCOUNT
    {
        public Nullable<decimal> CODE_COMBINATION_ID { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public string ACCOUNT_DESCRIPTION { get; set; }
        public short IS_ACTIVE { get; set; }
    }
}
