//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_EMPLOYEE
    {
        public Nullable<int> PERSON_ID { get; set; }
        public string EMPLOYEE_NUMBER { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public string EMPLOYEE_STATUS { get; set; }
        public string EMIRATES_ID { get; set; }
        public Nullable<long> DEPT_ID { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public Nullable<decimal> DIVISION_ID { get; set; }
        public string DIVISION_NAME { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string NATIONALITY_ID { get; set; }
        public string NATIONLITY_NAME { get; set; }
        public Nullable<System.DateTime> EFFICTIVE_DATE { get; set; }
        public string PRESENT_ADDRESS { get; set; }
        public string PO_BOX { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public short IS_ACTIVE { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public Nullable<short> IS_SUBCONTRACTOR { get; set; }
        public string EMPLOYEE_CARD_SERIAL { get; set; }
    }
}
