//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_STATUS
    {
        public INVOICE_STATUS()
        {
            this.INVOICE = new HashSet<INVOICE>();
            this.INVOICE_STATUS_HISTORY = new HashSet<INVOICE_STATUS_HISTORY>();
        }
    
        public int STATUS_ID { get; set; }
        public string EN_NAME { get; set; }
        public short IS_ACTIVE { get; set; }
        public string AR_NAME { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual ICollection<INVOICE> INVOICE { get; set; }
        public virtual ICollection<INVOICE_STATUS_HISTORY> INVOICE_STATUS_HISTORY { get; set; }
    }
}
