//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVOICE_STATUS_HISTORY
    {
        public int INVOICE_STATUS_HISTORY_ID { get; set; }
        public System.DateTime DATE_TIME { get; set; }
        public int STATUS_ID { get; set; }
        public Nullable<int> INVOICE_ID { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual INVOICE INVOICE { get; set; }
        public virtual INVOICE_STATUS INVOICE_STATUS { get; set; }
    }
}
