//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public LOCATION()
        {
            this.DEPOT = new HashSet<DEPOT>();
            this.LOCATION1 = new HashSet<LOCATION>();
            this.SHIFT = new HashSet<SHIFT>();
            this.CARD_CENTER = new HashSet<CARD_CENTER>();
        }
    
        public int LOCATION_ID { get; set; }
        public Nullable<int> ADDRESS_ID { get; set; }
        public string LOCATION_NAME { get; set; }
        public string LOCATION_AR_SHORT_NAME { get; set; }
        public string LOCATION_EN_SHORT_NAME { get; set; }
        public Nullable<int> LOCATION_TYPE_ID { get; set; }
        public Nullable<int> PARENT_LOCATION_ID { get; set; }
        public string PHONE_NUMBER { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public string FAX { get; set; }
        public string AR_LOCATION_NAME { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<short> IS_TOPUP_ALLOWED { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        public virtual ICollection<DEPOT> DEPOT { get; set; }
        public virtual ICollection<LOCATION> LOCATION1 { get; set; }
        public virtual LOCATION LOCATION2 { get; set; }
        public virtual ICollection<SHIFT> SHIFT { get; set; }
        public virtual ICollection<CARD_CENTER> CARD_CENTER { get; set; }
    }
}
