//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTIFICATION_MESSAGE
    {
        public string MESSAGE_CODE { get; set; }
        public string MESSAGE_DESCRIPTION { get; set; }
        public string MESSAGE_BODY { get; set; }
        public string AR_MESSAGE_BODY { get; set; }
        public string MESSAGE_SUBJECT { get; set; }
        public string AR_MESSAGE_SUBJECT { get; set; }
        public short MESSAGE_TYPE { get; set; }
        public Nullable<short> MESSAGE_GROUP { get; set; }
        public short IS_ACTIVE { get; set; }
        public int MESSAGE_NOTIFICATION_ID { get; set; }
        public Nullable<decimal> LIFE_TIME { get; set; }
        public Nullable<decimal> PRIORITY { get; set; }
        public Nullable<decimal> MUST_SEND { get; set; }
    }
}
