//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public PRODUCT()
        {
            this.RESTRICTION_GROUP_PRODUCT = new HashSet<RESTRICTION_GROUP_PRODUCT>();
            this.PRODUCT_PRICE_UPLIFT = new HashSet<PRODUCT_PRICE_UPLIFT>();
            this.RESTRICTION_GROUP_QUANTITY = new HashSet<RESTRICTION_GROUP_QUANTITY>();
        }
    
        public int PRODUCT_ID { get; set; }
        public string EN_NAME { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<short> IS_DRY { get; set; }
        public string AR_NAME { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<int> INTEGRATION_ID { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<decimal> IS_SERVICE { get; set; }
        public string COLOR_CODE { get; set; }
        public string INTEGRATION_CODE { get; set; }
        public Nullable<decimal> PRODUCT_CATEGORY_ID { get; set; }
        public string MEASUREUNIT { get; set; }
    
        public virtual ICollection<RESTRICTION_GROUP_PRODUCT> RESTRICTION_GROUP_PRODUCT { get; set; }
        public virtual ICollection<PRODUCT_PRICE_UPLIFT> PRODUCT_PRICE_UPLIFT { get; set; }
        public virtual ICollection<RESTRICTION_GROUP_QUANTITY> RESTRICTION_GROUP_QUANTITY { get; set; }
    }
}
