//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQST_REQUEST_CUSTOMER_CONTACT
    {
        public int REQUEST_CUSTOMER_ID { get; set; }
        public int REQUEST_CONTACT_ID { get; set; }
        public int CONTACT_TYPE_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual CONTACT_TYPE CONTACT_TYPE { get; set; }
        public virtual RQST_REQUEST_CONTACT RQST_REQUEST_CONTACT { get; set; }
    }
}
