//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQST_REQUEST_ATTACHEMENT
    {
        public int REQUEST_ATTACHMENT_ID { get; set; }
        public int REQUEST_ID { get; set; }
        public int REQUEST_DOCUMENT_ID { get; set; }
        public byte[] ATTACHMENT { get; set; }
        public string FILE_EXTENSION { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
    }
}
