//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQST_RQST_CUSTOMER_CNTCT_HIST
    {
        public int REQUEST_CUSTOMER_ID { get; set; }
        public int REQUEST_CONTACT_ID { get; set; }
        public int CONTACT_TYPE_ID { get; set; }
    
        public virtual RQST_REQUEST_CONTACT_HIST RQST_REQUEST_CONTACT_HIST { get; set; }
    }
}
