//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RQST_REQUEST_CUSTOMER_ADDRESS
    {
        public int REQUEST_ADDRESS_ID { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public Nullable<int> CITY_ID { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public string POST_CODE { get; set; }
        public string DETAILED_ADDRESS { get; set; }
        public string FAX { get; set; }
        public string PHONE_NUMBER { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
    }
}
