//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_MESSAGE
    {
        public int MESSAGE_ID { get; set; }
        public string MESSAGE_BODY { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public Nullable<short> IS_SENT { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public Nullable<System.DateTime> MESSAGE_DATE_TIME { get; set; }
        public string JOB_ID { get; set; }
        public Nullable<int> TOKEN_ID { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
