//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATION
    {
        public STATION()
        {
            this.RESTRICTION_GROUP_STATIONS = new HashSet<RESTRICTION_GROUP_STATIONS>();
        }
    
        public int STATION_ID { get; set; }
        public string EN_NAME { get; set; }
        public Nullable<int> STATION_GROUP_ID { get; set; }
        public string AR_NAME { get; set; }
        public short IS_ACTIVE { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
        public Nullable<int> CMS_LOCATION_ID { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<decimal> LAST_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
    
        public virtual ICollection<RESTRICTION_GROUP_STATIONS> RESTRICTION_GROUP_STATIONS { get; set; }
        public virtual STATION_GROUP STATION_GROUP { get; set; }
    }
}
