//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKEN_STATUS_CHANGE_HISTORY
    {
        public int STATUS_CHANGE_LOG_ID { get; set; }
        public int TOKEN_ID { get; set; }
        public int TOKEN_STATUS_ID { get; set; }
        public Nullable<int> TOKEN_STATUS_REASON_ID { get; set; }
        public System.DateTime STATUS_CHANGE_DATE_TIME { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual TOKEN TOKEN { get; set; }
        public virtual TOKEN_STATUS TOKEN_STATUS { get; set; }
        public virtual TOKEN_STATUS_REASON TOKEN_STATUS_REASON { get; set; }
        public virtual USERS USERS { get; set; }
    }
}
