//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKEN_TYPE
    {
        public TOKEN_TYPE()
        {
            this.TOKEN = new HashSet<TOKEN>();
            this.TOKEN_IIN = new HashSet<TOKEN_IIN>();
        }
    
        public int TOKEN_TYPE_ID { get; set; }
        public string EN_NAME { get; set; }
        public short IS_ACTIVE { get; set; }
        public string DESCRIPTION { get; set; }
        public string AR_NAME { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual ICollection<TOKEN> TOKEN { get; set; }
        public virtual ICollection<TOKEN_IIN> TOKEN_IIN { get; set; }
    }
}
