//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKEN
    {
        public TOKEN()
        {
            this.RESTRICTION_GROUP_TOKEN = new HashSet<RESTRICTION_GROUP_TOKEN>();
            this.TOKEN_STATUS_CHANGE_HISTORY = new HashSet<TOKEN_STATUS_CHANGE_HISTORY>();
        }
    
        public int TOKEN_ID { get; set; }
        public string CODE { get; set; }
        public int TOKEN_TYPE_ID { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<int> RESTRICTION_GROUP_ID { get; set; }
        public Nullable<int> NUMBER_OF_ACTIVE_TAGS { get; set; }
        public Nullable<int> TOKEN_STATUS_ID { get; set; }
        public Nullable<int> TOKEN_STATUS_REASON_ID { get; set; }
        public Nullable<short> IS_STATUS_INHERITED { get; set; }
        public Nullable<int> WORK_ORDER_ID { get; set; }
        public Nullable<int> PERSONALIZATION_ORDER_ID { get; set; }
        public string SERIAL { get; set; }
        public string SECOND_SERIAL { get; set; }
        public string TOKEN_CHIP_NUMBER { get; set; }
        public string SECOND_TOKEN_CHIP_NUMBER { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public Nullable<int> BENEFICIARY_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> VEHICLE_INFO_ID { get; set; }
        public Nullable<System.DateTime> REGISTERATION_DATE { get; set; }
        public Nullable<int> STATUS_CHANGE_LOG_ID { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<int> CUSTOM_EXPIRY_YEARS { get; set; }
        public Nullable<short> IS_TRX_NOTIFY { get; set; }
        public Nullable<System.DateTime> ISSUANCE_DATE { get; set; }
        public Nullable<short> IS_FEE_WAIVED_OFF { get; set; }
        public Nullable<decimal> ISSUANCE_TYPE_ID { get; set; }
        public Nullable<decimal> IS_MANUAL_DEFECT { get; set; }
        public string THIRD_SERIAL { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ICollection<RESTRICTION_GROUP_TOKEN> RESTRICTION_GROUP_TOKEN { get; set; }
        public virtual TOKEN_TYPE TOKEN_TYPE { get; set; }
        public virtual VEHICLE_INFO VEHICLE_INFO { get; set; }
        public virtual TOKEN_STATUS TOKEN_STATUS { get; set; }
        public virtual TOKEN_STATUS_REASON TOKEN_STATUS_REASON { get; set; }
        public virtual ICollection<TOKEN_STATUS_CHANGE_HISTORY> TOKEN_STATUS_CHANGE_HISTORY { get; set; }
        public virtual WORK_ORDER WORK_ORDER { get; set; }
    }
}
