//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOKEN_IIN
    {
        public int TOKEN_IIN_ID { get; set; }
        public Nullable<int> TOKEN_TYPE_ID { get; set; }
        public Nullable<int> TOKEN_IIN1 { get; set; }
        public short IS_ACTIVE { get; set; }
    
        public virtual TOKEN_TYPE TOKEN_TYPE { get; set; }
    }
}
