//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public USERS()
        {
            this.ACCOUNT_MANAGER = new HashSet<ACCOUNT_MANAGER>();
            this.SHIFT = new HashSet<SHIFT>();
            this.SHIFT1 = new HashSet<SHIFT>();
            this.BENEFICIARY_STATUS_CHANGE_LOG = new HashSet<BENEFICIARY_STATUS_CHANGE_LOG>();
            this.CUSTOMER_STATUS_CHANGE_LOG = new HashSet<CUSTOMER_STATUS_CHANGE_LOG>();
            this.TOKEN_STATUS_CHANGE_HISTORY = new HashSet<TOKEN_STATUS_CHANGE_HISTORY>();
            this.RQST_REQUEST_CONTACT = new HashSet<RQST_REQUEST_CONTACT>();
        }
    
        public int USER_ID { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public string OBJECTS_ID { get; set; }
        public string JOB_TITLE { get; set; }
        public string USER_NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public short IS_ACTIVE { get; set; }
        public short IS_CSP_USER { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<ACCOUNT_MANAGER> ACCOUNT_MANAGER { get; set; }
        public virtual ICollection<SHIFT> SHIFT { get; set; }
        public virtual ICollection<SHIFT> SHIFT1 { get; set; }
        public virtual ICollection<BENEFICIARY_STATUS_CHANGE_LOG> BENEFICIARY_STATUS_CHANGE_LOG { get; set; }
        public virtual ICollection<CUSTOMER_STATUS_CHANGE_LOG> CUSTOMER_STATUS_CHANGE_LOG { get; set; }
        public virtual ICollection<TOKEN_STATUS_CHANGE_HISTORY> TOKEN_STATUS_CHANGE_HISTORY { get; set; }
        public virtual ICollection<RQST_REQUEST_CONTACT> RQST_REQUEST_CONTACT { get; set; }
    }
}
