//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE_REGISTER
    {
        public VEHICLE_REGISTER()
        {
            this.VEHICLE_INFO = new HashSet<VEHICLE_INFO>();
        }
    
        public int VEHICLE_REGISTER_ID { get; set; }
        public int MAKE_ID { get; set; }
        public int MODEL_ID { get; set; }
        public Nullable<int> YEAR { get; set; }
        public int INVENTORY_UNIT_TYPE_ID { get; set; }
        public Nullable<int> CC { get; set; }
        public Nullable<decimal> FUEL_INLET { get; set; }
        public Nullable<decimal> FUEL_CAPACITY { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual ICollection<VEHICLE_INFO> VEHICLE_INFO { get; set; }
        public virtual VEHICLE_MODEL VEHICLE_MODEL { get; set; }
        public virtual VEHICLE_MAKE VEHICLE_MAKE { get; set; }
    }
}
