//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE_INFO_DUMMY
    {
        public int VEHICLE_INFO_ID { get; set; }
        public string PLATE_NUMBER { get; set; }
        public int VEHICLE_YEAR { get; set; }
        public string TYPE_CODE { get; set; }
        public string MAKE_NAME_EN { get; set; }
        public string MAKE_NAME_AR { get; set; }
        public string MODEL_NAME_EN { get; set; }
        public string MODEL_NAME_AR { get; set; }
        public string CHASSIS_NUMBER { get; set; }
        public string ENGINE_NUMBER { get; set; }
        public Nullable<int> CC { get; set; }
        public string FUEL_INLET { get; set; }
        public Nullable<int> FUEL_CAPACITY { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    }
}
