//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEEK_DAYS
    {
        public WEEK_DAYS()
        {
            this.RESTRICTION_GROUP_WEEKDAY = new HashSet<RESTRICTION_GROUP_WEEKDAY>();
        }
    
        public int WEEK_DAY_ID { get; set; }
        public string EN_NAME { get; set; }
        public string AR_NAME { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<short> IS_START_DAY_OF_WEEK { get; set; }
        public Nullable<decimal> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
    
        public virtual ICollection<RESTRICTION_GROUP_WEEKDAY> RESTRICTION_GROUP_WEEKDAY { get; set; }
    }
}
