//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DUC.CMS.CustomerService.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORK_ORDER
    {
        public WORK_ORDER()
        {
            this.TOKEN = new HashSet<TOKEN>();
            this.WORK_ORDER_STATUS_HISTORY = new HashSet<WORK_ORDER_STATUS_HISTORY>();
        }
    
        public int WORK_ORDER_ID { get; set; }
        public string WORK_ORDER_NUMBER { get; set; }
        public Nullable<int> WORK_ORDER_STATUS_ID { get; set; }
        public Nullable<int> VEHICLE_INFO_ID { get; set; }
        public Nullable<int> VEHICLE_DEPOT_ID { get; set; }
        public Nullable<System.DateTime> APPOINTMENT_DATE_TIME { get; set; }
        public Nullable<System.DateTime> ACTUAL_SERVICE_DATE_TIME { get; set; }
        public int PASSED_QUALITY_TEST { get; set; }
        public Nullable<int> WORK_ORDER_TYPE_ID { get; set; }
        public Nullable<int> LAST_UPDATED_USER_ID { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<int> WORK_ORDER_REASON_ID { get; set; }
        public short IS_ACTIVE { get; set; }
        public Nullable<int> RECIPIENT_ID_TYPE { get; set; }
        public string RECIPIENT_ID_NUMBER { get; set; }
        public Nullable<decimal> LAST_LOCATION_ID { get; set; }
        public Nullable<System.DateTime> APPOINT_TILL_DATE_TIME { get; set; }
    
        public virtual DEPOT DEPOT { get; set; }
        public virtual IDENTIFICATION_TYPE IDENTIFICATION_TYPE { get; set; }
        public virtual ICollection<TOKEN> TOKEN { get; set; }
        public virtual VEHICLE_INFO VEHICLE_INFO { get; set; }
        public virtual WORK_ORDER_STATUS WORK_ORDER_STATUS { get; set; }
        public virtual WORK_ORDER_TYPE WORK_ORDER_TYPE { get; set; }
        public virtual ICollection<WORK_ORDER_STATUS_HISTORY> WORK_ORDER_STATUS_HISTORY { get; set; }
        public virtual WORK_ORDER_REASON WORK_ORDER_REASON { get; set; }
    }
}
